### ISSUE TITLE
FiveM

### ISSUE THREAD

**Issue by ghost** [AreWeAntiCheatYet/AreWeAntiCheatYet#1085]
### Game Title

FiveM

### Game Website

https://fivem.net/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

FiveM works, but the anti-cheat is disabled so you can't join any servers with svadhesive anti-cheat.

### Proof of Mention

https://cdn.discordapp.com/attachments/1007651324835418143/1059930211480768572/Screenshot_20230103_212410.png

**Comment by Curve** [comment]
Probably more like broken, doesn't look like they outright stated they won't support wine at all

**Comment by Faalagorn** [comment]
It seems it's related to implementation of shared resources in DXVK which probably won't happen anytime soon if at all: https://github.com/doitsujin/dxvk/issues/899

**Comment by Etaash-mathamsetty** [comment]
> It seems it's related to implementation of shared resources in DXVK which probably won't happen anytime soon if at all: [doitsujin/dxvk#899](https://github.com/doitsujin/dxvk/issues/899)

except they are already supported and have been for a while because halo infinite needs them as well, https://github.com/doitsujin/dxvk/blob/132bc529c3b809b1290af5ad839685972cf34f01/src/d3d11/d3d11_device.cpp#L2261

**Comment by Bitwolfies** [comment]
Wish I had my source but the FiveM team stated they wont go out of their way to add support, but if it it ends up working over Proton and doesn't cause any issues, they will allow it just fine.

**Comment by YvanCywan** [comment]
It is unsupported, however, the anti-cheat is likely never to work.

> > It seems it's related to implementation of shared resources in DXVK which probably won't happen anytime soon if at all: [doitsujin/dxvk#899](https://github.com/doitsujin/dxvk/issues/899)
> 
> That's not related to the AntiCheat but yeah, I think that issue degrades the games usability

This has been resolved for since mid 2022, it prevented FiveM from even running properly, nothing to do with the status of anti-cheat:
https://www.gamingonlinux.com/2022/03/dxvk-1101-is-out-with-initial-support-for-shared-resources/

**Comment by Etaash-mathamsetty** [comment]
> It is unsupported, however, the anti-cheat is likely never to work.
> 
> > > It seems it's related to implementation of shared resources in DXVK which probably won't happen anytime soon if at all: [doitsujin/dxvk#899](https://github.com/doitsujin/dxvk/issues/899)
> > 
> > 
> > That's not related to the AntiCheat but yeah, I think that issue degrades the games usability
> 
> This has been resolved for since mid 2022, it prevented FiveM from even running properly, nothing to do with the status of anti-cheat: [gamingonlinux.com/2022/03/dxvk-1101-is-out-with-initial-support-for-shared-resources](https://www.gamingonlinux.com/2022/03/dxvk-1101-is-out-with-initial-support-for-shared-resources/)
> 
> The best hope for anyone wishing to use fivem effectively will be dual booting/VM.

why don't you test it by hiding wine exports and sending a log?

**Comment by Curve** [comment]
> > It is unsupported, however, the anti-cheat is likely never to work.
> > > > It seems it's related to implementation of shared resources in DXVK which probably won't happen anytime soon if at all: [doitsujin/dxvk#899](https://github.com/doitsujin/dxvk/issues/899)
> > > 
> > > 
> > > That's not related to the AntiCheat but yeah, I think that issue degrades the games usability
> > 
> > 
> > This has been resolved for since mid 2022, it prevented FiveM from even running properly, nothing to do with the status of anti-cheat: [gamingonlinux.com/2022/03/dxvk-1101-is-out-with-initial-support-for-shared-resources](https://www.gamingonlinux.com/2022/03/dxvk-1101-is-out-with-initial-support-for-shared-resources/)
> > The best hope for anyone wishing to use fivem effectively will be dual booting/VM.
> 
> why don't you test it by hiding wine exports and sending a log?

Will wait for an update on this before changing anything about the status ^^

**Comment by Killercat103** [comment]
Well the DXVK issue does not really apply anymore as it was added late 2022 I believe. I tried running the game myself.
I installed FiveM as a steam game with the same steam compat data path as my GTA V installation. I had to make a workaround by setting the target platform to
Windows 7 because later platforms use UWP which does not seem to work on Linux.

I started a server locally and removed adhesive from a file named components.json and added sv_lan 1 to the config file as authentication failed. But after connecting to the server on localhost went fine and FiveM was entirely playable.

I would add it to the table as "Broken" all things considered

**Comment by Curve** [comment]
> Well the DXVK issue does not really apply anymore as it was added late 2022 I believe. I tried running the game myself.
> I installed FiveM as a steam game with the same steam compat data path as my GTA V installation. I had to make a workaround by setting the target platform to
> Windows 7 because later platforms use UWP which does not seem to work on Linux.
> 
> I started a server locally and removed adhesive from a file named components.json and added sv_lan 1 to the config file as authentication failed. But after connecting to the server on localhost went fine and FiveM was entirely playable.
> 
> I would add it to the table as "Broken" all things considered

Thanks for the thorough insight, I'll see if I can add this once I have time

**Comment by Etaash-mathamsetty** [comment]
DXVK issues are resolved with DXVK 2.3 (and native d3dcompiler)

**Comment by Curve** [comment]
> DXVK issues are resolved with DXVK 2.3 (and native d3dcompiler)

Does it run and work now or are there still any issues?

**Comment by Etaash-mathamsetty** [comment]
> > DXVK issues are resolved with DXVK 2.3 (and native d3dcompiler)
> 
> Does it run and work now or are there still any issues?

works, but no online

**Comment by YvanCywan** [comment]
> 

So what you're saying is that anti-cheat still doesn't work and is broken?

**Comment by Etaash-mathamsetty** [comment]
> > 
> 
> So what you're saying is that anti-cheat still doesn't work and is broken?

yep the anti cheat is still broken, but potentially with some collaboration with them could get it working.

**Comment by YvanCywan** [comment]
> > > 
> > 
> > 
> > So what you're saying is that anti-cheat still doesn't work and is broken?
> 
> yep the anti cheat is still broken, but potentially with some collaboration with them we could get it working.

Their anti-cheat isn't FOSS. 

They have stated multiple times that they won't actively put in the effort. The linux server is a very bad port that is only in existence because of their contract with Zap Hosting. The FiveM team is now part of R*/Take2.

Any collaboration with them is a pipe dream.

https://forum.cfx.re/t/is-adhesive-by-any-chance-ever-going-to-be-supported-over-fivem-proton/5120618/2?u=hebi_kotei

**Comment by Etaash-mathamsetty** [comment]
> > > > 
> > > 
> > > 
> > > So what you're saying is that anti-cheat still doesn't work and is broken?
> > 
> > yep the anti cheat is still broken, but potentially with some collaboration with them we could get it working.
> 
> Their anti-cheat isn't FOSS. 
> 
> They have stated multiple times that they won't actively put in the effort. The linux server is a very bad port that is only in existence because of their contract with Zap Hosting. The FiveM team is now part of R*/Take2.
> 
> Any collaboration with them is a pipe dream.
> 
> https://forum.cfx.re/t/is-adhesive-by-any-chance-ever-going-to-be-supported-over-fivem-proton/5120618/2?u=hebi_kotei

Ok so the collaboration part is not possible, but the anti cheat could potentially work through wine, I have to disassemble it and see what it's doing first
