### ISSUE TITLE
Update Watch_Dogs legion

### ISSUE THREAD

**Issue by Bitwolfies** [AreWeAntiCheatYet/AreWeAntiCheatYet#1095]
### Game Title

Watch_Dogs legion

### Status of the Anti-Cheat

Running.

### Proof of Mention

Nothing official, but it worked for me and they just enabled it for the division 2.

**Comment by Curve** [comment]
Did it run in multiplayer as well?
The Singleplayer is working for a while now for me without tinkering

**Comment by Bitwolfies** [comment]
I am referring to its online mode yes.

**Comment by Curve** [comment]
> I am referring to its online mode yes. 

Perfect, that's great news, thanks for confirming ^^

**Comment by ytfcon** [comment]
Is this only for the Steam version, or Ubisoft Connect, too?

**Comment by Bitwolfies** [comment]
> Is this only for the Steam version, or Ubisoft Connect, too? The Division 2 only had support on Steam, so I feel it's worth clarifying.

Since its battleeye I would assume so so long as you add the battleeye runtime it would work. Battleeye doesnt require an so file from the devs like eac. Just for them to send an email and the proton battleeye runtime.

**Comment by ytfcon** [comment]
After testing, it seems that it's still broken. Could not match with any other players (assumed to be due to low player population, but may be due to anti-cheat), and got a Boring-Yam error (BattlEye error) after around 15 minutes. ![Boring-Yam error (BattlEye error)](https://user-images.githubusercontent.com/63753664/222145860-e2b5d2ea-ceae-4d58-8dbe-494d51b96b01.png) 
Tried again, same thing happened.

**Comment by Bitwolfies** [comment]
Odd, game never kicked me out of anything I tried. Swear if this was some rare bypass I got.

**Comment by Curve** [comment]
> Odd, game never kicked me out of anything I tried. Swear if this was some rare bypass I got. Valve has it as unsupported on deck but it doesn't have the anti cheat as the reason why.

Could you test it again?
I'll leave this open for sometime until we have more reports

**Comment by ytfcon** [comment]
Can confirm the game works on Steam. A no-go for Ubisoft Connect, however, like my last report. A workaround will need to be found there.

**Comment by gardotd426** [comment]
>Since its battleeye I would assume so so long as you add the battleeye runtime it would work. Battleeye doesnt require an so file from the devs like eac. Just for them to send an email and the proton battleeye runtime.

How's that exactly? The BattlEye runtime 100% does include `.so` libraries - it has to, the BattlEye Proton/Wine support is identical to the EAC Proton/Wine support: They both use the already-existing native Linux clients to communicate with the game's Windows client. Both use `.so` files.

**Comment by gardotd426** [comment]
`find ~/.local/share/lutris/runtime/battleye_runtime | grep \\.so`:

```
/home/matt/.local/share/lutris/runtime/battleye_runtime/BEClient_x64.so
/home/matt/.local/share/lutris/runtime/battleye_runtime/v1/lib/wine/beclient.dll.so
/home/matt/.local/share/lutris/runtime/battleye_runtime/v1/lib64/wine/beclient_x64.dll.so
/home/matt/.local/share/lutris/runtime/battleye_runtime/BEClient.so
```

**Comment by ytfcon** [comment]
> > Since its battleeye I would assume so so long as you add the battleeye runtime it would work. Battleeye doesnt require an so file from the devs like eac. Just for them to send an email and the proton battleeye runtime.
> 
> How's that exactly? The BattlEye runtime 100% does include `.so` libraries - it has to, the BattlEye Proton/Wine support is identical to the EAC Proton/Wine support: They both use the already-existing native Linux clients to communicate with the game's Windows client. Both use `.so` files.

.so files as in ones bundled with the game, I assume. Most titles require that. I don't exactly see how this is relevant to the whole topic of "Is Watch_Dogs Legion running?", though.

**Comment by YajTPG** [comment]
Multiplayer works fine for me on Steam and on the Ubisoft Connect version, I boot up Ubisoft Connect as a non-steam game under Proton Experimental with the launch params:
`PROTON_BATTLEYE_RUNTIME="~/.local/share/Steam/steamapps/common/Proton BattlEye Runtime" DXVK_ASYNC=1 PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 VKD3D_CONFIG=dxr11 gamemoderun mangohud %command% -dx11`
Although the WDL launcher adds the `-BattlEyeLauncher` launch parameter to the main executable, which disables Battleye for the game, no idea how it still works fine for me.
I can also confirm that multiplayer does require BattlEye as I tried to disable Battleye in Windows and loading into free roam, I kept getting a `Boring-Yam` error

**Comment by gardotd426** [comment]
I tried it in Ubi Connect and after about 20 minutes in online play (with other people in the map) I got a Boring-Yam error. 

Also, just FYI `DXVK_ASYNC` is literally not a thing anymore unless you're using a REALLY old Proton GE version, it was never a thing in any official Proton build.

**Comment by begin-theadventure** [comment]
> Also, just FYI `DXVK_ASYNC` is literally not a thing anymore

dxvk-gplasync, and you can easily replace the DXVK version in Proton.

**Comment by ytfcon** [comment]
@gardotd426 [This is the output of find on my steam prefix.](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/files/11781620/findoutput.txt) It works with multiplayer, lasted around an hour without a kick in populated games.

**Comment by gardotd426** [comment]
What the hell? Your find doesn't report you having **any** of the dlls
included in the runtime. It only reports you having the 32 and 64-bit
belauncher.exe files in system32 and syswow64, and that's it.

Could you also give me a find on your game directory? Like the
steamapps/common directory as opposed to the compatdata/appid/pfx one.

Sorry I can't use code tags I'm replying by email.

**Comment by ytfcon** [comment]
@gardotd426 Lack of code tags weren't a bother. [Here you go.](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/files/11782776/wdl.txt)
