### ISSUE TITLE
Update Dead by Daylight

### ISSUE THREAD

**Issue by aleksasiriski** [AreWeAntiCheatYet/AreWeAntiCheatYet#1151]
### Game Title

Dead by Daylight

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

The link to discussion isn't working anymore, and I can't seem to find the discussion manually

### Proof of Mention

https://forum.deadbydaylight.com/en/discussion/comment/3265320/#Comment_3265320

**Comment by Curve** [comment]
Why was this closed?

**Comment by aleksasiriski** [comment]
Because I dislike stale issues

**Comment by Curve** [comment]
> Because I dislike stale issues

Sorry to not have closed it already I've been very busy lately...

In case you can't wait PRs are always welcome as I can mostly approve them instantly ^^

**Comment by Curve** [comment]
> I would gladly make a PR but...
> 
> > I can't seem to find the discussion

I'd just remove the link if it's invalid anyway, at least that's what I planned to do :D

**Comment by NoaLRX** [comment]
If anyone wants the method posted (then deleted) on the forum to play DBD on steam deck via epic games, here it is:

If you don't trust the link [here is the method:](https://web.archive.org/web/20221220051802/https://forums.bhvr.com/dead-by-daylight/discussion/282110/eac-on-steam-deck-proton-linux/p26)

```
Step by step:

Get DBD from the Epic Games Store -- which is free btw
Download Heroic Launcher and attach it to your EGS account so it will see that version of DBD
Go into Steam and make sure Proton EasyAntiCheat Runtime is installed. You can find it in your Library if you change the view-mode from "Games" to "Tools" -- It's between the search bar and the home button on the left side of the steam UI
Right click Proton EasyAntiCheat Runtime and go to Manage => Browse Local Files and either take note of the path to this folder, or move up one folder and copy the entire folder somewhere easy to remember.
In Heroic Launcher click the gear icon to go to settings on DBD. Make sure some version of Proton is selected as the "Wine Version", people have said basically any version of experimental or GE works. You can easily download different versions of wine inside Heroic if you need to in the "Wine Manager" section of the menu on the left side. Make sure "EasyAntiCheat Runtime" is DISABLED. Scroll down a bit, make sure "Use Steam Runtime" is DISABLED. Under "Environment Variables" add the following in the first box PROTON_EAC_RUNTIME and in the second box put the path to the Steam Proton EasyAntiCheat Runtime from the previous step.
That's it. Launch the game and you should be able to play multiplayer. There is currently no way to link your Steam account to your EGS account, so if EGS is not your primary way of playing then you're starting at level 1 with nothing.

EDIT: Adding info provided by user _ManlyMaid

U still have to:

" In the game directory copy the EasyAntiCheat folder to DeadByDaylight/Binaries/EGS/" (or link it)
```


Someone had the good idea to save the page on the web archive or it will be deleted

**Comment by milochadam** [comment]
> I would gladly make a PR but...
> 
> > I can't seem to find the discussion

I believe only the format of URL changed, link from OP:
https://forums.bhvr.com/dead-by-daylight/discussion/comment/3265320/#Comment_3265320
link from post above:
https://forums.bhvr.com/dead-by-daylight/discussion/comment/3293469/#Comment_3293469

**Comment by Curve** [comment]
> > I would gladly make a PR but...
> > 
> > > I can't seem to find the discussion
> 
> I believe only the format of URL changed, link from OP:
> https://forums.bhvr.com/dead-by-daylight/discussion/comment/3265320/#Comment_3265320
> link from post above:
> https://forums.bhvr.com/dead-by-daylight/discussion/comment/3293469/#Comment_3293469

Nice!
Will update this once I have time
