### ISSUE TITLE
Request THE FINALS

### ISSUE THREAD

**Issue by Redemption198** [AreWeAntiCheatYet/AreWeAntiCheatYet#1184]
### Game Title

THE FINALS

### Game Website

https://www.reachthefinals.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://www.protondb.com/app/2073850

**Comment by Starz0r** [comment]
Missed the first playtest, will re-evaluate if there is another, or the game releases.

**Comment by Starz0r** [comment]
Going to add this one and simply mark it as Broken. If it changes, feel free to re-open this issue with the new information, or submit a new ticket.

**Comment by noodlejetski** [comment]
while there hasn't been any changes yet, according to the info from their Discord (ugh) supporting Linux is "on their list".

![ResizedImage_2023-10-29_10-24-08_1347](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/8598559/6ccee19e-a2b1-4d3f-a1e6-bd89c263f408)

**Comment by noodlejetski** [comment]
update: the game now works with Proton Experimental
