### ISSUE TITLE
Update Hell Let Loose

### ISSUE THREAD

**Issue by Florian7843** [AreWeAntiCheatYet/AreWeAntiCheatYet#1222]
### Game Title

Het Let Loose

### Status of the Anti-Cheat

🕧 Planned

### Proof of Mention

https://www.youtube.com/watch?t=386&v=DJqh61nfuTs&feature=youtu.be

**Comment by Starz0r** [comment]
The website already reflects this, and even links to the same video. Commit where the relevant change took place: https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/commit/6f09dca9a2d5c2fc306497af75ee9a03e6adf41e.
