### ISSUE TITLE
Request Roblox

### ISSUE THREAD

**Issue by Jack5079** [AreWeAntiCheatYet/AreWeAntiCheatYet#1247]
### Game Title

Roblox

### Game Website

https://roblox.com

### Anti-Cheat Software

Planned

### Status of the Anti-Cheat

Denied

### Tinkering Steps

~~`roblox-player:1+launchmode:app+channel:zlive` to revert x64 client, won't work once fully rolled out~~ It's fully rolled out

### Proof of Mention

https://devforum.roblox.com/t/the-new-roblox-64-bit-byfron-client-forbids-wine-users-from-using-it-most-likely-unintentional/2305528/2

**Comment by Curve** [comment]
Doesn't it work with one GitHub project?

Can't quite remember which it was but I think it's this one https://devforum.roblox.com/t/grapejuice-easily-run-roblox-on-linux/262949

**Comment by Jack5079** [comment]
@Curve It used to, now Studio is broken for everyone and people in the Byfron A/B test cannot use Player ![image](https://user-images.githubusercontent.com/29169102/233725662-fe06a30b-0e4a-4884-b57b-10070f7efcd6.png)

**Comment by Curve** [comment]
> @Curve It used to, now Studio is broken for everyone and people in the Byfron (new anticheat) A/B test cannot use Player ![image](https://user-images.githubusercontent.com/29169102/233725662-fe06a30b-0e4a-4884-b57b-10070f7efcd6.png)
> 

From what I've gathered it seems that it works for some people?  
And only the x64 client is broken, right? Is there a way to enforce usage of the x86 client?

**Comment by Jack5079** [comment]
> > @Curve It used to, now Studio is broken for everyone and people in the Byfron (new anticheat) A/B test cannot use Player ![image](https://user-images.githubusercontent.com/29169102/233725662-fe06a30b-0e4a-4884-b57b-10070f7efcd6.png)
> 
> From what I've gathered it seems that it works for some people? And only the x64 client is broken, right? Is there a way to enforce usage of the x86 client?

Yes, the `roblox-player:1+launchmode:app+channel:zlive` link reverts to x86 but once Byfron is fully rolled out it will no longer work

**Comment by Curve** [comment]
> > > @Curve It used to, now Studio is broken for everyone and people in the Byfron (new anticheat) A/B test cannot use Player ![image](https://user-images.githubusercontent.com/29169102/233725662-fe06a30b-0e4a-4884-b57b-10070f7efcd6.png)
> > 
> > From what I've gathered it seems that it works for some people? And only the x64 client is broken, right? Is there a way to enforce usage of the x86 client?
> 
> Yes, the `roblox-player:1+launchmode:app+channel:zlive` link reverts to x86 but once Byfron is fully rolled out it will no longer work

Is that the case?
GOG stated that it is supposedly only because of information gathering regarding stability of the new client - however I'm not sure how much I'd believe that as it sounds kind of suspicious

**Comment by birthtothunder** [comment]
Maybe planned would be more appropriate, per the [roblox admin](https://devforum.roblox.com/t/the-new-roblox-64-bit-byfron-client-forbids-wine-users-from-using-it-most-likely-unintentional/2305528/2):
> Wine is not officially supported but we are committed to working towards compatibility where possible. Unfortunately, I cannot provide a specific timeline for this support. However, I assure you that it remains a priority for our team.

**Comment by somerandomguy24** [comment]
The byfron client has now been fully rolled out, so the workaround no longer works, and the anticheat software is [Hyperion](https://www.pockettactics.com/roblox/hyperion) (which is already listed on AWACY.

**Comment by Jack5079** [comment]
Denied
![image](https://user-images.githubusercontent.com/29169102/236951220-4016b589-2726-4fd6-98ee-70cfa87e8317.png)

**Comment by somerandomguy24** [comment]
[Source](https://devforum.roblox.com/t/proper-support-for-the-linux-platform/56544/88)

**Comment by Jack5079** [comment]
![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/29169102/b6d53f64-81a1-49a8-be6d-d02d1e784dfb)

**Comment by somerandomguy24** [comment]
So I guess the status is now "planned"?

**Comment by somerandomguy24** [comment]
Also, [source](https://devforum.roblox.com/t/proper-support-for-the-linux-platform/56544/120)
