### ISSUE TITLE
Xdefiant works no tinkering 

### ISSUE THREAD

**Issue by papamikey** [AreWeAntiCheatYet/AreWeAntiCheatYet#1259]
Halfway through the beta they enabled the anti cheat server side. Me and some others posted about out experiences in the Linux post of the Ubisoft discord server. Runs perfectly find and is supported.

**Comment by Curve** [comment]
> https://discord.com/channels/863058244934696961/1090191984456646699 here is the link we talked about it in

Could you attach a screenshot of the conversation?

**Comment by papamikey** [comment]
> > https://discord.com/channels/863058244934696961/1090191984456646699 here is the link we talked about it in
> 
> Could you attach a screenshot of the conversation?

![Screenshot_20230426_065854_Discord](https://user-images.githubusercontent.com/97386118/234555714-514cc437-4443-4213-be64-bdacbccccee3.png)
![Screenshot_20230426_065929_Discord](https://user-images.githubusercontent.com/97386118/234555717-992a9db8-ea74-4a56-a491-645db316454d.png)

**Comment by elhuevoegg** [comment]
Can confirm, works amazing during the closed beta. Didn't work at the start of it, but was enabled without a patch of any kind later on

**Comment by Redemption198** [comment]
True, i also played in the beta (not on the day it started) on Fedora

**Comment by ThePelicano** [comment]
At first for me it didn't work, but after I saw the feedback on Discord I tested it and it worked perfectly.
