### ISSUE TITLE
Update Dead by Daylight

### ISSUE THREAD

**Issue by birthtothunder** [AreWeAntiCheatYet/AreWeAntiCheatYet#1265]
### Game Title

Dead by Daylight

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention
DBD seems to be enabled on Steam Linux again, I think it'd be good to wait a day or two though before changing it to Supported as they could pull the plug like they did last time.

https://www.protondb.com/app/381210
https://www.reddit.com/r/linux_gaming/comments/133zc2h/dead_by_daylight_on_steam_now_works_on_linux_with/
EDIT: It appears they are officially supporting it
https://steamdeckhq.com/news/steam-dead-by-daylight-is-now-working-on-deck/
https://store.steampowered.com/news/app/381210/view/3723958226061651097?l=english

**Comment by qwertychouskie** [comment]
https://steamdeckhq.com/news/steam-dead-by-daylight-is-now-working-on-deck/

Support is official now!  :tada:

**Comment by Drostina** [comment]
Wanted to drop this link in from them officially since I haven't seen it here on this issue: https://store.steampowered.com/news/app/381210/view/3723958226061651097?l=english
