### ISSUE TITLE
Update Vermintide 2 to Broken

### ISSUE THREAD

**Issue by akdean** [AreWeAntiCheatYet/AreWeAntiCheatYet#1271]
### Game Title

Vermintide 2

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

I don't think this should be rated as "Running" as it's so inconsistent.

It worked _okay_ for a while there, but sporadic breakages and tedious "workarounds" are problematic. 

On the Steam Deck, some days it works, some days it doesn't. On the desktop (Fedora) it works less often than it works.

I think it's disengenuous to tag it as Running, so propose a "Broken" update.

### Proof of Mention

https://github.com/ValveSoftware/Proton/issues/1528

**Comment by akdean** [comment]
I do plan to try and debug this at some point, but it's not high on my priority list, for now this is just to stop people getting false hope. 

It should also be noted that 'Running' was always a bit dubious as you needed to host the game, and this might not be feasible for some people.

**Comment by SlouchyButton** [comment]
I think this should be revisited, as at least workaround does exist and there is still a community behind this game.

You need patched game, as GameSpy servers are long dead, but this patch replaces the GameSpy servers with community ones. http://team-simple.org/download/

I tested this and was able to play multiple games using the original retail version of the game - I suppose origin should work too. Apart from this patch nothing else is needed - game works out of the box via soda (Bottles, but expect wine as well).

**Comment by delentef** [comment]
Hello,

> http://team-simple.org/download/

This link send to a BattelField 1942/Vietnam site, is it normal? What should I download there, and how do I use what I have downloaded? Thanks for hints!

**Comment by CheckYourFax** [comment]
Devs moved over to EGS version of EAC, so it works on Proton now.
