### ISSUE TITLE
Update For Honor

### ISSUE THREAD

**Issue by Lamdarer** [AreWeAntiCheatYet/AreWeAntiCheatYet#1272]
### Game Title

For Honor

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Nothing specific, maybe something along those lines for SteamDeck(?): `PROTON_EAC_RUNTIME="/home/deck/.local/share/Steam/steamapps/common/Proton EasyAntiCheat Runtime/" %command% uplay://launch.569/0`

### Proof of Mention

https://www.protondb.com/app/304390#NZwmVLh0PR
https://www.protondb.com/app/304390#EYb2Q93_MH

There is a total of 3 Working reports since 2 Weeks ago. But I haven't tested it yet myself so in case this is not yet enough evidence you could hold of for now. Edit: I tested it myself and I could indeed play Multiplayer PvE and PvP

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently. I had a similar issue. I contacted metamask directly and they had it resolved for me. 
alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by gibarel1** [comment]
Can confirm it works, but i had to use proton 7.0-6 , both experimental (crashed upon reachin the main menu), GE (crashed on the ubisoft launcher) and 8 (didnt even launch) did not work.

**Comment by RadiantOblivion** [comment]
Can confirm it works with GE-Proton-7-55. Requires to first log into Ubisoft Connect on first launch; close out the game; then relaunch and it and it will open perfectly.

**Comment by Domefemia** [comment]
This is the update where they added the eac support file for linux: https://steamdb.info/patchnotes/10988960/
