### ISSUE TITLE
Update Rainbow Six Siege

### ISSUE THREAD

**Issue by FlashyReese** [AreWeAntiCheatYet/AreWeAntiCheatYet#1288]
### Game Title

Rainbow Six Siege

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

The Ubisoft forums closed a few weeks ago. To show your support, you need to do so on their Discord server in a channel called `#game-feedback` and the thread called `Linux/Steam Deck Support for Rainbow Six: Siege/Extraction.`

### Proof of Mention

https://forums.ubisoft.com/

**Comment by kazelin** [comment]
They have a bug tracker website as well. The link might be able to be updated to the latest one: https://r6fix.ubi.com/projects/RAINBOW6-SIEGE-LIVE/issues/LIVE-49179
