### ISSUE TITLE
Update Diabotical

### ISSUE THREAD

**Issue by Sid127** [AreWeAntiCheatYet/AreWeAntiCheatYet#1308]
### Game Title

Diabotical

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps
Requires a custom compiled wine package available [here](https://github.com/Etaash-mathamsetty/wine-diabotical/releases/) at the moment. 

Also requires a symlink from `xaudio2_9redist.dll` as `xaudio2_9.dll`  in the installation directory and the corresponding wine override for it

### Proof of Mention

https://www.reddit.com/r/Diabotical/comments/13rkzvi/how_to_run_diabotical_on_linux/

**Comment by Etaash-mathamsetty** [comment]
I just wanted to mention that they switched to EAC from EQU8

**Comment by Sid127** [comment]
Not sure if I should open a new issue for this, but as of wine 8.11, custom wine is no longer required. Still needs the xaudio workaround, however
