### ISSUE TITLE
Update Smite

### ISSUE THREAD

**Issue by birthtothunder** [AreWeAntiCheatYet/AreWeAntiCheatYet#1320]
### Game Title

Smite

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

> SMITE will now run on Linux systems – Special thanks to the SMITE community for helping with this. A group of players in the r/smite discord made a big impact on this change

### Proof of Mention

https://www.smitegame.com/news/the-season-of-souls-10-6-update-notes/

**Comment by BearZA-91** [comment]
So according to https://www.youtube.com/watch?v=GVc4Jxl0zxY&t=3328s
They are still testing and whatnot, but the latest reports on Protondb have a fix, you just move files into the right folder.
https://www.protondb.com/app/386360

**Comment by birthtothunder** [comment]
Works OOTB now it seems
https://www.protondb.com/app/386360#BkAC2Z0wfh
