### ISSUE TITLE
Update Fall Guys

### ISSUE THREAD

**Issue by gardotd426** [AreWeAntiCheatYet/AreWeAntiCheatYet#1327]
### Game Title

Fall Guys

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

You no longer need to do any workarounds. The only "workaround" is using Proton Experimental, you no longer need the EAC workaround from Proton GE. 

[Latest Proton GE release notes](https://github.com/gloriouseggroll/proton-ge-custom/releases):

```
protonfixes: remove no longer needed fall guys easyanticheat_x64.so workaround (Thanks Corben)
```

### Proof of Mention

https://github.com/gloriouseggroll/proton-ge-custom/releases

**Comment by gardotd426** [comment]
Actually, I would say supported, since it works with both EGS and Steam, it must be intentional.

**Comment by therealmate** [comment]
Now it needs another workaround: https://www.reddit.com/r/FallGuysGame/comments/13dn570/comment/jjqmh9w/?context=3

**Comment by birthtothunder** [comment]
https://www.protondb.com/app/1097150#HJH_hmqRcM
Works OOTB according to this user

**Comment by gardotd426** [comment]
I actually can't get it to work at all. Doesn't work out of the box here.

**Comment by birthtothunder** [comment]
Do you have Proton EasyAntiCheat installed?

**Comment by gardotd426** [comment]
Yes, I play Apex every day.
