### ISSUE TITLE
Request Nikke: Goddess of Victory

### ISSUE THREAD

**Issue by Hairo** [AreWeAntiCheatYet/AreWeAntiCheatYet#1354]
### Game Title

Nikke: Goddess of Victory

### Game Website

https://nikke-en.com/

### Anti-Cheat Software

Anti-Cheat Expert

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/112w8bk/nikke_pc_installer/

**Comment by d-kja** [comment]
Hey, I finally managed to run this game under Arch. Here are the steps: https://gist.github.com/d-kja/74633df5f2d6e55cb2a77c3f9d6acece

<img width="2692" height="1421" alt="Image" src="https://github.com/user-attachments/assets/aa2d2ec0-cbb0-4a32-bb40-692a8f231180" />

Also, I already played a bit and it's working perfectly fine! I'm not sure if it's bannable though, we'll have to wait and see
