### ISSUE TITLE
Update <For honor>

### ISSUE THREAD

**Issue by pinduzera** [AreWeAntiCheatYet/AreWeAntiCheatYet#1357]
### Game Name

For Honor

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

It has been working without issues since the last update. (never required the susggested workarounds)
Now there is an official statement that EAC works on Steam Deck.

### Proof of Mention

https://www.ubisoft.com/en-us/game/for-honor/news-updates/6jz99oXbJUVyK5h17fp6B8/patch-notes-2451-for-honor

**Comment by birthtothunder** [comment]
It should be under Supported then.

**Comment by gibarel1** [comment]
The notes specifically mentioned that it now should work on the steam deck, doesn't that mean it should be tagged as "supported"?
