### ISSUE TITLE
Update Roblox

### ISSUE THREAD

**Issue by birthtothunder** [AreWeAntiCheatYet/AreWeAntiCheatYet#1360]
### Game Title

Roblox

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

It still requires Grapejuice or Vinegar.

### Proof of Mention

https://devforum.roblox.com/t/why-did-roblox-stop-supporting-linux-users/2444335/61?u

**Comment by Curve** [comment]
> ### Game Title
> 
> Roblox
> 
> ### Status of the Anti-Cheat
> 
> 👍 Running
> 
> ### Tinkering Steps
> 
> It still requires Grapejuice.
> 
> ### Proof of Mention
> 
> https://devforum.roblox.com/t/why-did-roblox-stop-supporting-linux-users/2444335/61?u

The proof of mention links to a private post, can you share any screenshots or a page dump by any chance?

**Comment by birthtothunder** [comment]
![Screenshot_20230813_095308](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/121361374/1ac36065-f876-44b2-b5f1-efd9c9a961eb)
The update hasnt been rolled out yet

**Comment by iFlxy** [comment]
> now it has ![image](https://user-images.githubusercontent.com/16343162/262141617-f29ca3f9-8d07-403f-abc2-c9b8846d0df7.png)

wait what. It's still "Wine is not supported." for me.

**Comment by apprehensions** [comment]
Do not add this. Roblox still hasn't fully rolled out this.

You have to use an unstable release channel; or in other words a beta version, for roblox to function on Wine.

**Comment by LeadRDRK** [comment]
Roblox is now playable on the LIVE channel (stable release) as of version `429d03ccdcbb4161`.

**Comment by Etaash-mathamsetty** [comment]
this should be changed to supported not just running

**Comment by birthtothunder** [comment]
No, because it still requires other software

**Comment by Etaash-mathamsetty** [comment]
> No, because it still requires other software

True, but I think the rating should at least get updated first...

**Comment by Curve** [comment]
> No, because it still requires other software

What's required?

**Comment by Etaash-mathamsetty** [comment]
> > No, because it still requires other software
> 
> What's required?

Nothing, they think that using grapejuice/vinegar is required for some reason

**Comment by HtB1526** [comment]
> > ### Название игры
> > Roblox
> > ### Статус Античита
> > 👍 Бег
> > ### Этапы работы
> > Для этого по-прежнему требуется грейпджус.
> > ### Доказательство упоминания
> > https://devforum.roblox.com/t/why-did-roblox-stop-supporting-linux-users/2444335/61?u
> 
> Доказательство упоминания ссылается на личный пост, можете ли вы случайно поделиться какими-либо скриншотами или дампом страницы?



> > ### Game Title
> > Roblox
> > ### Status of the Anti-Cheat
> > 👍 Running
> > ### Tinkering Steps
> > It still requires Grapejuice.
> > ### Proof of Mention
> > https://devforum.roblox.com/t/why-did-roblox-stop-supporting-linux-users/2444335/61?u
> 
> The proof of mention links to a private post, can you share any screenshots or a page dump by any chance?
![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/93080546/42e26c45-9244-4bcb-986d-47ef7067efc4)

**Comment by apprehensions** [comment]
@Starz0r Grapejuice is currently unmaintained and Roblox does not run using Grapejuice, neither does Roblox Studio.

**Comment by Etaash-mathamsetty** [comment]
yes, the replacement is vinegar
