### ISSUE TITLE
Update Survarium

### ISSUE THREAD

**Issue by Faalagorn** [AreWeAntiCheatYet/AreWeAntiCheatYet#1362]
### Game Title

Survarium

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

Survarium is long gone now, closed over a year ago and not likely to return, I guess it should be removed.

### Proof of Mention

https://survarium.com/

**Comment by birthtothunder** [comment]
Should just be removed then

**Comment by Faalagorn** [comment]
Yes, it is now removed, thanks!
