### ISSUE TITLE
Update Dead by Daylight

### ISSUE THREAD

**Issue by muznyo** [AreWeAntiCheatYet/AreWeAntiCheatYet#1365]
### Game Title

Dead by Daylight

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Steam version works, Epic version doesn't

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/15pjk1h/is_there_any_way_to_play_the_epic_games_version/
https://www.reddit.com/r/SteamDeck/comments/15q628j/dead_by_daylight_on_steam_deck_with_epic_games/
Also it's mentioned in Heroic Games Launcher discord server
Also tried it myself

**Comment by birthtothunder** [comment]
It shouldnt be switched to Broken, just add it as a note that the epic version doesnt work.

**Comment by clanps** [comment]
Would also be good to mention that it is steam deck verified so I would consider it supported. Before purchasing it on steam, I tried it on epic games and it would sometimes work but it would break a lot from update to update.
