### ISSUE TITLE
Update Rainbow 6 extraction

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [AreWeAntiCheatYet/AreWeAntiCheatYet#1380]
### Game Title

Rainbow 6 extraction

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Rainbow 6 extraction works on linux now (even on AMD)

### Proof of Mention

https://www.protondb.com/app/2379390

**Comment by fschaupp** [comment]
Thx for the update.
Those time I wanted wait a bit after the SD fix, to check, if it's just a short-time fix or a long lasting state. 👍
