### ISSUE TITLE
Update Honkai Star Rail

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [AreWeAntiCheatYet/AreWeAntiCheatYet#1384]
### Game Title

Honkai Star Rail

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Have to use a special launcher

### Proof of Mention

https://lutris.net/games/honkai-star-rail/

**Comment by Drostina** [comment]
Curious to know if the said launcher does get you banned? I've played Genshin, all seems fine, but I've heard this game does get you banned. If anyone has clocked a few hours into this, I'd be grateful to know

**Comment by cybik** [comment]
-1. Use of the launcher and current Lutris integrations involves explicit TOS violations, and so the game should *not* be marked as running.

**Comment by pbogut** [comment]
```
Running
Games that will run on Linux without impact on online gameplay but may require you to perform certain tinkering steps (This does not include any means of explicitly bypassing the anti-cheat)
```

If it worked out of the box it would be *Supported*. Unless special launcher is there to mess with anticheat, I would say it fits *Running* description.

**Comment by Etaash-mathamsetty** [comment]
> -1. Use of the launcher and current Lutris integrations involves explicit TOS violations, and so the game should *not* be marked as running.

Then why is genshin marked as running, or at least it has a note that there are workarounds available

**Comment by cybik** [comment]
> 
> Then why is genshin marked as running, or at least it has a note that there are workarounds available 

Genshin Impact runs without any modifications or patches at this point.

**Comment by cybik** [comment]
> If it worked out of the box it would be *Supported*. Unless special launcher is there to mess with anticheat, I would say it fits *Running* description.
The launcher messes with the anticheat. Therefore, -1.

**Comment by Etaash-mathamsetty** [comment]
Ok fair enough, but this should be added as a note at the very least

**Comment by Etaash-mathamsetty** [comment]
> it is though? https://areweanticheatyet.com/game/honkai-star-rail
> 
> Mentioning "a launcher" would help discovery, which is something AreWeAntiCheatYet shouldn't itself do. the mission statement of the site is "tell which games' anticheat are working", not "workaround enablement" - if anything, "workaround enablement" would allow gamedevs to get this repo offline on grounds of "helping modders and crackers to disable game security".
> 
> Which we're not helping by discussing it in the issues but I digress.

This was already done with genshin impact, the website just says at least 2 workarounds available or something last time I checked. Same thing could be done here, and there was a time where the launcher was linked on areqeanticheatyer

**Comment by cybik** [comment]
> and btw there was a time where the launcher for genshin was linked on areweanticheatyet

Yeah, I know. I was the one who asked to get that taken down.

**Comment by Renari** [comment]
I do think it would be fair to mention workaround available without any links similarly to how Genshin was before.

**Comment by Renari** [comment]
afaik star rail should not be listed as `running` for reasons outlined in this issue, the game does not run unless you use 3rd party fixes that modify the game for example look at Honkai Impact 3rd, it is in a similar state and is listed as broken

**Comment by Renari** [comment]
@Starz0r @cybik Afaik star rail should not be listed as `running` for reasons outlined in this issue, the game does not run unless you use 3rd party fixes that modify the game, for example look at Honkai Impact 3rd, it is in a similar state and is listed as broken. This is how this was handled with Genshin originally as well.

**Comment by Curve** [comment]
> @Starz0r @cybik Afaik star rail should not be listed as `running` for reasons outlined in this issue, the game does not run unless you use 3rd party fixes that modify the game, for example look at Honkai Impact 3rd, it is in a similar state and is listed as broken. This is how this was handled with Genshin originally as well.

If a third party launcher is required that messes with the game in a similar way to Genshin I absolutely agree on this

**Comment by Renari** [comment]
I did some testing in a bottle, wine-ge-proton8-25, dxvk 2.0 similar to my setup in the workaround. The launcher runs, and will install the game however after patching is completed the game will not launch.

**Comment by cybik** [comment]
> @Starz0r @cybik Afaik star rail should not be listed as `running` for reasons outlined in this issue, the game does not run unless you use 3rd party fixes that modify the game, for example look at Honkai Impact 3rd, it is in a similar state and is listed as broken. This is how this was handled with Genshin originally as well.
> 
> As such https://github.com/AreWeAntiCheatYet/master-manifest/commit/78a38d9204fef71c57db9f20ab33b5102ccb1154 should be reverted.

I fully agree and had said as such.
