### ISSUE TITLE
Request add Heaven Burns Red

### ISSUE THREAD

**Issue by bayazidbh** [AreWeAntiCheatYet/AreWeAntiCheatYet#1390]
### Game Title

Heaven Burns Red ( ヘブンバーンズレッド )

### Game Website

https://heaven-burns-red.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://www.protondb.com/app/1973710

**Comment by Starz0r** [comment]
After doing more research, it appears that this may not be using any type of anti-cheat, but instead an anti-tamper wrapper called CrackProof? Not exactly sure if this fits being on the list.

**Comment by Starz0r** [comment]
It appears that the developers of CrackProof themselves consider it to be in the same space as "Easy Anti-Cheat" for [protecting against "fraud"](https://automaton-media.com/articles/interviewsjp/20211214-185768/).
