### ISSUE TITLE
Update Hell Let Loose

### ISSUE THREAD

**Issue by MattyGWS** [AreWeAntiCheatYet/AreWeAntiCheatYet#1409]
### Game Title

Hell Let Loose

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

People are reporting hell let loose is working now;

https://www.reddit.com/r/linux_gaming/comments/16v2ula/hell_let_loose_works_on_linux_now/

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/16v2ula/hell_let_loose_works_on_linux_now/

**Comment by ahmouse15** [comment]
Also reports of it working from [ProtonDB](https://www.protondb.com/app/686810), and Bronze rated (e.g. playable)

**Comment by Al3x-and3r** [comment]
Can confirm.
