### ISSUE TITLE
Update Rec Room

### ISSUE THREAD

**Issue by CharlesCanlom** [AreWeAntiCheatYet/AreWeAntiCheatYet#1427]
### Game Title

Rec Room

### Status of the Anti-Cheat

🕧 Planned

### Tinkering Steps

This was said by a Staff Member named Star Centurion. He also said that the game is switching EAC versions, and that it's gonna be before early 2024. Photo was sent to a thread by a Community Mod Manager.

### Proof of Mention

https://cdn.discordapp.com/attachments/1020390284552589342/1167984082542678146/IMG_7827.png?ex=65501cf1&is=653da7f1&hm=862b136a65b84202a3e7e7e0d6bda227e8410538c7a19b87d267c7d15a7506dd&

**Comment by Starz0r** [comment]
Appears that the game is working and running as of 2024, so I'll be moving it straight to the `Running` status instead.
