### ISSUE TITLE
Update Apex Legends

### ISSUE THREAD

**Issue by sh3zb0t** [AreWeAntiCheatYet/AreWeAntiCheatYet#1428]
### Game Title

Apex Legends

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

easyanticheat_x64.so missing from public build, completely breaking EAC compatability

### Proof of Mention

recent comments on https://www.protondb.com/app/1172470 as well as testing for myself

**Comment by Curve** [comment]
What a shame, probably worth waiting a few days to ensure this was not a mistake

**Comment by sh3zb0t** [comment]
I've been searching for an update on this matter and I'm getting mixed reports
it's either working again or a tinker required according to this [post at reddit](https://www.reddit.com/r/linux_gaming/comments/te2i42/apex_legends_eac_is_kicking_linux_users_out_of/)

**Comment by Unionizing** [comment]
Hyperion's also listed on apex legends when only Roblox has Hyperion.

**Comment by Etaash-mathamsetty** [comment]
this can be closed, it's working as of today

**Comment by otter501** [comment]
it still has the hyperion anticheat despite that anti-vheat being Roblox exclusive
