### ISSUE TITLE
Update the cycle frontier

### ISSUE THREAD

**Issue by koloved** [AreWeAntiCheatYet/AreWeAntiCheatYet#1431]
### Game Title

the cycle frontier

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

The game is officially dead from 27 september

### Proof of Mention

https://store.steampowered.com/news/app/868270/view/3685681434321802502

**Comment by Faalagorn** [comment]
Wouldn't it be better to simply remove it then?
