### ISSUE TITLE
Update Hunt: Showdown

### ISSUE THREAD

**Issue by Aman9das** [AreWeAntiCheatYet/AreWeAntiCheatYet#1461]
### Game Title

Hunt: Showdown

### Status of the Anti-Cheat

🕧 Planned

### Tinkering Steps

The situation on this game went from playable and deck verified to getting anti-cheat errors

### Proof of Mention

https://www.gamingonlinux.com/2023/11/hunt-showdown-is-broken-on-steam-deck-linux-due-to-easy-anti-cheat/

**Comment by ak-42** [comment]
Already done in #1458. Although your reference is better than the one I used.

**Comment by Aman9das** [comment]
Great thanks!
