### ISSUE TITLE
Update League of Legends

### ISSUE THREAD

**Issue by sh3zb0t** [AreWeAntiCheatYet/AreWeAntiCheatYet#1490]
### Game Title

League of Legends

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

seems to be not working under wine for quite few months already, needs to be updated at this point

### Proof of Mention

https://leagueoflinux.org/status/

**Comment by ImUrX** [comment]
it's been broken for 19 days, [here](https://forums.lutris.net/t/league-of-legends-reconnect-loop/19240) you can see one of the relevant posts where a riot employee appears

**Comment by sh3zb0t** [comment]
Sorry, it was more empirical since I am a league addict and it feels like forever

**Comment by RParodia** [comment]
I don't play League so have no idea if this actually works, but according to [this post on Reddit](https://www.reddit.com/r/leagueoflinux/comments/180lp0b/comment/kczq58f/) it can be made to work again

**Comment by sh3zb0t** [comment]
yep, there is indeed a fix, finally! GOD if felt like ages
