### ISSUE TITLE
Update Fortnite

### ISSUE THREAD

**Issue by ghost** [AreWeAntiCheatYet/AreWeAntiCheatYet#1496]
### Game Title

Fortnite

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

It's running, but partially.
Used latest Wine-GE from Heroic. Then it says that it was not started correctly.

### Proof of Mention

https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/119664251/7b4c5a2d-e557-45f9-b5d4-403b61cc887e

**Comment by FocusBlast** [comment]
I feel "Partial" is not the right word. If the game had let us at least get into the practice zone, we could claim it was running partially. There are many games that exhibit this behavior; one of them is The Finals. Also, there's no way it'd start working all of a sudden when we consider [Tim Sweeney's recent statements](https://www.pcgamer.com/epic-ceo-tim-sweeney-says-hes-open-to-fortnite-on-steam-or-any-serious-store-but-that-the-end-of-these-ridiculous-30-fees-is-a-requirement/).

**Comment by gibarel1** [comment]
> I feel "Partial" is not the right word. If the game had let us at least get into the practice zone, we could claim it was running partially. There are many games that exhibit this behavior; one of them is The Finals. Also, there's no way it'd start working all of a sudden when we consider [Tim Sweeney's recent statements](https://www.pcgamer.com/epic-ceo-tim-sweeney-says-hes-open-to-fortnite-on-steam-or-any-serious-store-but-that-the-end-of-these-ridiculous-30-fees-is-a-requirement/).

even if it was brought to steam, it would still need to enable linux compatibility on eac, which does not need steam, so the statement is irrelevant for gaming on linux.

**Comment by Starz0r** [comment]
Yeah, this game is still broken, even now. Just because you might be able to launch the game, or go into the editor for a little bit does not mean it's working. It's either all or nothing, and I'll continue to keep this game at "Denied" until they change their behavior.
