### ISSUE TITLE
Add note to League of Legends

### ISSUE THREAD

**Issue by ElecDashi** [AreWeAntiCheatYet/AreWeAntiCheatYet#1509]
League of Legends will not be supported for much longer, as Riot Games will make Vanguard, the same kernel-level anti cheat that VALORANT uses, a requirement for playing League of Legends in the future. They say it should arrive in late February or late March, but they also say that it will be a requirement "starting in a few weeks" so the exact date when LoL will cease working is not known.
On Reddit, it was already confirmed that they will not support Wine.

I suggest to add a note stating that it will most likely stop working in the future.

Proof of mention
Anti Cheat arriving:
https://www.youtube.com/watch?v=9U_jEzKf0_0&t=732s

Riot Games Staff stating that Wine is not supported:
https://www.reddit.com/r/leagueoflegends/comments/18za7o7/comment/kgh17uo/

**Comment by Curve** [comment]
What a shame, no idea why they would think that league needs a kernel level ac

Would you mind submitting a PR for this?

**Comment by Linuxydable** [comment]
Because the creator of the anticheat ItsGamerDoc: [https://twitter.com/itsGamerDoc](https://twitter.com/itsGamerDoc) are against the Open Source community...

<img width="844" alt="image" src="https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/33342705/8330690b-38cc-4eec-a6de-c5165af57da4">
![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/33342705/d6b4ee8c-76fe-429d-9d6e-31f64daf7c57)

**Comment by ElecDashi** [comment]
Created a pull request, will close this issue

**Comment by gibarel1** [comment]
> Because a developer of the anticheat ItsGamerDoc: https://twitter.com/itsGamerDoc are against the Open Source community...
> 
> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/33342705/294723004-8330690b-38cc-4eec-a6de-c5165af57da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjU2NjcsIm5iZiI6MTcwNDY2NTM2NywicGF0aCI6Ii8zMzM0MjcwNS8yOTQ3MjMwMDQtODMzMDY5MGItMzhjYy00ZWVjLWE2ZGUtYzUxNjVhZjU3ZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MjI0M2Y1Mjg2YzAzOGFiNDIwYTQ5M2JiMTk5OTllNzgwYjZkY2I3YWYzZDRiMmExZWViNWIxODUwMjRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1LN2yyYmSt9U1v6n6qonZCtHIYtzGgFRmqdqU4pNDI">
> ![image](https://private-user-images.githubusercontent.com/33342705/294723039-b9d68365-3103-489d-b456-37bd20fee87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjU2NjcsIm5iZiI6MTcwNDY2NTM2NywicGF0aCI6Ii8zMzM0MjcwNS8yOTQ3MjMwMzktYjlkNjgzNjUtMzEwMy00ODlkLWI0NTYtMzdiZDIwZmVlODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNzYzYzBlZDhjOGYyYjllNTgxMmZhMzEwZjBkZjk3YWFjMWU0Y2VhM2EyZDY4OWIxNDJhMTkzMzBhYWQxZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISxSO6cc6UVmBFyh9Ir51JDwUuSx5cKfrOwCjIzg0Do)

all that talk to then have the MacOS client not need vanguard, smells like BS to me

**Comment by Curve** [comment]
> > Because a developer of the anticheat ItsGamerDoc: https://twitter.com/itsGamerDoc are against the Open Source community...
> > 
> > <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/33342705/294723004-8330690b-38cc-4eec-a6de-c5165af57da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjU2NjcsIm5iZiI6MTcwNDY2NTM2NywicGF0aCI6Ii8zMzM0MjcwNS8yOTQ3MjMwMDQtODMzMDY5MGItMzhjYy00ZWVjLWE2ZGUtYzUxNjVhZjU3ZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MjI0M2Y1Mjg2YzAzOGFiNDIwYTQ5M2JiMTk5OTllNzgwYjZkY2I3YWYzZDRiMmExZWViNWIxODUwMjRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1LN2yyYmSt9U1v6n6qonZCtHIYtzGgFRmqdqU4pNDI">
> > ![image](https://private-user-images.githubusercontent.com/33342705/294723039-b9d68365-3103-489d-b456-37bd20fee87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjU2NjcsIm5iZiI6MTcwNDY2NTM2NywicGF0aCI6Ii8zMzM0MjcwNS8yOTQ3MjMwMzktYjlkNjgzNjUtMzEwMy00ODlkLWI0NTYtMzdiZDIwZmVlODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNzYzYzBlZDhjOGYyYjllNTgxMmZhMzEwZjBkZjk3YWFjMWU0Y2VhM2EyZDY4OWIxNDJhMTkzMzBhYWQxZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISxSO6cc6UVmBFyh9Ir51JDwUuSx5cKfrOwCjIzg0Do)
> 
> all that talk to then have the MacOS client not need vanguard, smells like BS to me

Lmfao as if that would pose a less significant attack vector
