### ISSUE TITLE
Update Valorant

### ISSUE THREAD

**Issue by Linuxydable** [AreWeAntiCheatYet/AreWeAntiCheatYet#1510]
### Game Title

Valorant

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

ItsGamerDoc [https://twitter.com/itsGamerDoc](https://twitter.com/itsGamerDoc) a developer of Riot Vanguard Anti Cheat is against a Linux support because "_linux has too much attack surface_".

![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/33342705/266b364f-8964-4ae2-9cc4-58e2fd5f9947)

![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/33342705/afe6d72d-a906-43ff-b7f0-1affa258c9e4)

### Proof of Mention

https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/33342705/266b364f-8964-4ae2-9cc4-58e2fd5f9947

**Comment by iFlxy** [comment]
Very unnecessary comment, but that was easy to predict. Their motto is "obscurity is security". I also heard about other statements from Riot Anti-Cheat devs about Linux support that said similar things, I will edit this comment if I find them.
