### ISSUE TITLE
Update Black Desert Online

### ISSUE THREAD

**Issue by Inq-B** [AreWeAntiCheatYet/AreWeAntiCheatYet#1520]
### Game Title

Black Desert Online

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Anticheat needs to be updated to XIGNCODE3; with the move to XIGNCODE, Black Desert now runs under Linux with minor issues. 

Ignoring my package count:

![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/38569387/3741d445-f54d-4b7b-9f5e-abb5982f7d78)

### Proof of Mention

https://www.naeu.playblackdesert.com/en-US/News/Detail?groupContentNo=6458&countryType=de-DE

**Comment by Curve** [comment]
I thought they switched to EAC?

**Comment by Inq-B** [comment]
they did indeed go XIGNCODE > EAC > back to XIGNCODE.

**Comment by Curve** [comment]
> they did indeed go XIGNCODE > EAC > back to XIGNCODE. 

Amazing, wouldn't have expected to ever see BDO running on Linux
