### ISSUE TITLE
Update PROJECT: PLAYTIME

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [AreWeAntiCheatYet/AreWeAntiCheatYet#1529]
### Game Title

PROJECT: PLAYTIME

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Game is working on my machine as well. Also why the lack of updates on this repo?

### Proof of Mention

https://www.protondb.com/app/1961460

**Comment by Starz0r** [comment]
> Game is working on my machine as well. Also why the lack of updates on this repo?

What do you mean? I've updated the manifest on this repo every day for the last week? Are you referring to something else?

**Comment by Etaash-mathamsetty** [comment]
> > Game is working on my machine as well. Also why the lack of updates on this repo?
> 
> What do you mean? I've updated the manifest on this repo every day for the last week? Are you referring to something else?

I've had issues open here for months at this point with no action, so i was just wondering

**Comment by Starz0r** [comment]
> > > Game is working on my machine as well. Also why the lack of updates on this repo?
> > 
> > 
> > What do you mean? I've updated the manifest on this repo every day for the last week? Are you referring to something else?
> 
> I've had issues open here for months at this point with no action, so i was just wondering

We're still slowly going through the backlog. New features are being made to make this process slightly easier and faster, but they're not ready yet for prime time. Plus, the repository is going through a slight refactor in the background, so all of this has to be juggled on top of the work that already needs to be done.

**Comment by Etaash-mathamsetty** [comment]
> > > > Game is working on my machine as well. Also why the lack of updates on this repo?
> > > 
> > > 
> > > What do you mean? I've updated the manifest on this repo every day for the last week? Are you referring to something else?
> > 
> > 
> > I've had issues open here for months at this point with no action, so i was just wondering
> 
> We're still slowly going through the backlog. New features are being made to make this process slightly easier and faster, but they're not ready yet for prime time. Plus, the repository is going through a slight refactor in the background, so all of this has to be juggled on top of the work that already needs to be done.

nice work you guys are doing, thanks
