### ISSUE TITLE
Update Enlisted

### ISSUE THREAD

**Issue by ToRRent1812** [AreWeAntiCheatYet/AreWeAntiCheatYet#1539]
### Game Title

Enlisted

### Status of the Anti-Cheat

🕧 Planned

### Proof of Mention

https://steamcommunity.com/app/2051620/discussions/0/4205867749040592896/

**Comment by Berikai** [comment]
Enlisted supports Steam Deck now!

https://store.steampowered.com/news/app/2051620/view/6718890930823507462?l=english
