### ISSUE TITLE
Request <Plants vs. Zombies Garden Warfare 2>

### ISSUE THREAD

**Issue by cynder66** [AreWeAntiCheatYet/AreWeAntiCheatYet#1544]
### Game Title

Plants vs. Zombies Garden Warfare 2

### Game Website

https://www.ea.com/games/plants-vs-zombies/plants-vs-zombies-garden-warfare-2

### Anti-Cheat Software

EA Anticheat

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

"...to create a safe and fair experience for all players, we will be rolling out an update in March 2024 that will transition PVZGW2 for PC over to EA Anticheat... Additionally, Plants vs. Zombies Garden Warfare 2 will not run on the native Steam OS for Steamdeck with this update."

### Proof of Mention

https://www.ea.com/games/plants-vs-zombies/plants-vs-zombies-garden-warfare-2/news/pvzgw2-anticheat-update

**Comment by duckymomo360** [comment]
This game ran flawless on the steam deck. What a shame that the engine doesnt have basic replication security. Would've prevented this entirely. Seriously, have you seen the cheats people use in it? MFers be playing as literal boss NPCS in multiplayer. EA wtf were u thinking.
