### ISSUE TITLE
Update War Thunder

### ISSUE THREAD

**Issue by engemil** [AreWeAntiCheatYet/AreWeAntiCheatYet#1557]
### Game Title

War Thunder

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

War Thunder seem to be working on native linux (not the most optimal version). However, with proton, the Easy Anti-cheat is not initialized, making the best way to run War Thunder on Linux, not possible to run modes that requires EAC. I would classify this as not optimal or broken.

### Proof of Mention

https://www.protondb.com/app/236390#D3AvuaBKXN

**Comment by nyuware** [comment]
Im playing war thunder daily on native and I've never had a single crash.

**Comment by Starz0r** [comment]
Looks like the game is still working for the majority of Linux players. Perhaps there is an issue with your setup?
