### ISSUE TITLE
Update Battlefield V

### ISSUE THREAD

**Issue by mizztgc** [AreWeAntiCheatYet/AreWeAntiCheatYet#1558]
### Game Title

Battlefield™ V

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

The game will no longer work on Linux/Steam Deck due to EA AntiCheat being implemented on April 3rd

### Proof of Mention

https://steamcommunity.com/app/1238810/discussions/0/4355617246781704749/

**Comment by Curve** [comment]
This is such a shame
