### ISSUE TITLE
Update Intruder

### ISSUE THREAD

**Issue by DEPSUT** [AreWeAntiCheatYet/AreWeAntiCheatYet#1559]
### Game Title

Intruder

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

New Intruder update introduced experimental Steam Proton support for Linux Gaming, it is still experimental but the game seems to be running relatively well.
You can check the patch notes on the latest update with the mention of Steam Proton support

### Proof of Mention

https://steamdb.info/patchnotes/13913874/#experimental-linux-compatibility-other-housekeeping

**Comment by NaterEST** [comment]
been playing the game for 703 h in total (around 100 or so h have been on linux), I was one of the main testers for the game linux (in Secret Base Alpha), and it just works flawlessly on stable proton as well. Even though they said "experimental", it works perfectly.
