### ISSUE TITLE
It be would a cool feature if the site listed whether or not the games have micro transactions or not.

### ISSUE THREAD

**Issue by linlinxza** [AreWeAntiCheatYet/AreWeAntiCheatYet#1563]
It be would a cool feature if the site listed whether or not the games have micro transactions or not. I would like to see the amount of games with micro transaction that do and don't work on Proton, versus the amount of games that have no micro transactions that do and don't work on Proton. It would be interesting to see the comparisons.

**Comment by Starz0r** [comment]
Hey, this is very much out of scope for this project! However the [PCGamingWiki](https://www.pcgamingwiki.com/) does include some of the information you're seeking, so maybe you should look there? The information on our site is very much narrowly scoped towards anti-cheats, and occasionally anti-tamper tools when necessary.
