### ISSUE TITLE
Update <Gray Zone Warfare>

### ISSUE THREAD

**Issue by sim590** [AreWeAntiCheatYet/AreWeAntiCheatYet#1617]
### Game Title

Gray Zone Warfare

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

For now, there is no reference on the areweanticheatyet website, so here is a new reference to add for the game. I tested the game and I got:

![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/4147254/ab784f4e-d2f7-46be-ab23-3dcebcbb29e7)

### Proof of Mention

https://www.protondb.com/app/2479810

**Comment by sim590** [comment]
Actually, it seems like the report needs some time to be indexed on the page. Until the next refresh, it won't show. Don't know how much time it will take...

**Comment by sim590** [comment]
The feed has actually been updated with multiple reports. You could update the website with this info.

**Comment by MattiasHansson** [comment]
EAC is enabled.. Just a matter of getting the game to work smoothly now :)
