### ISSUE TITLE
Update Dead By Daylight

### ISSUE THREAD

**Issue by OlivierFRDierick** [AreWeAntiCheatYet/AreWeAntiCheatYet#1619]
### Game Title

Dead By Daylight

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Hello,

I propose that the first note **Enabled on Steam and Epic Games Store** be changed to **Steam version supported** and the second note be replaced with a **Show your support for the Epic Games Store version** link to the [bug report](https://forums.bhvr.com/dead-by-daylight/discussion/412813/pc-linux-proton-cant-run-the-epic-games-store-version-on-the-steamos-linux) I've opened.

Regards.

### Proof of Mention

https://forums.bhvr.com/dead-by-daylight/discussion/412813/pc-linux-proton-cant-run-the-epic-games-store-version-on-the-steamos-linux

**Comment by OlivierFRDierick** [comment]
Hello,

My forum bug report was closed for being a 'technical issue' and so I went to the support website.

I filed a request for support at Behaviour Digital and it was closed after the support staff stated that Linux is not supported (See attachment).

However contradicting this is with the SteamDeck verified status, Behaviour Digital is officially not supporting Linux (at least any version of the game on non-SteamDeck Linux and non-steam version of the game on the SteamDeck).

So please, update the AreWeAntiCheatYet game notes accordingly : 1. Steam version Supported, 2. Epic Games version Broken.

Regards.

![Behaviour Digital ticket 1517868](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/53239162/11cfab04-6e63-4c4c-8735-55d07d65d968)

**Comment by StarterX4** [comment]
Epic version officially unsupported. They don't care. "Buy Steam version or don't play".
