### ISSUE TITLE
Update supposed Anticheat for Arena Breakout: Infinite

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [AreWeAntiCheatYet/AreWeAntiCheatYet#1630]
### Game Title

Arena Breakout: Infinite

### Status of the Anti-Cheat

:question: Unknown

### Tinkering Steps

It is using ACE Anticheat instead of the supposed EasyAntiCheat.

### Proof of Mention

https://twitter.com/AntiCheatPD/status/1791269132626763924

**Comment by Starz0r** [comment]
Did you mean to mark this as `Denied`? Did the developers say they aren't going to work on supporting Linux? Alternatively, do the ACE devs have a anti-Linux stance that made you mark it like you did?

**Comment by PoorPocketsMcNewHold** [comment]
> [**@Starz0r**](https://github.com/Starz0r) commented on [May 19, 2024, 1:20 AM GMT+2](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/issues/1630#issuecomment-2119027475):
> 
> > Did you mean to mark this as `Denied`? Did the developers say they aren't going to work on supporting Linux? Alternatively, do the ACE devs have a anti-Linux stance that made you mark it like you did?

Actually, nope. It's just the Github template, that asked me to add a status. I'll edit it normally to confirm the unconfirmed status.
