### ISSUE TITLE
Update iRacing

### ISSUE THREAD

**Issue by DanFraserUK** [AreWeAntiCheatYet/AreWeAntiCheatYet#1632]
### Game Title

iRacing

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Adding iRacing to Steam, either originally purchased there or by obtaining a Steam key from the iRacing Account Management page.

Install iRacing in Steam, then download the installer from the iRacing website.  Using protontricks-launch --appid 266410 [installer executable path] and point the installer to the Steam install location.

Once installed, use Proton Experimental or GE-Proton9.3/4/5 and play.  UI is laggy due to Electron shenanigans but game is completely playable.

The reason iRacing is now playable on Linux is due to iRacing changing from EasyAntiCheat to EpicOnlineServices.  The initial change was reverted after two weeks but then reinstated 7 weeks later.

### Proof of Mention

Uh, me!  Writing threads on the iRacing forums (needs account to view)

**Comment by Schutzend** [comment]
![image](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/76664156/694d2809-a925-410a-bbcd-9af5f4ac6926)

**Comment by Schutzend** [comment]
Currently I'm sending emails to the support of a lot of games to find out if they want to support their Anticheat on Linux and IRacing just replied to me

**Comment by DanFraserUK** [comment]
> ![image](https://private-user-images.githubusercontent.com/76664156/334565341-694d2809-a925-410a-bbcd-9af5f4ac6926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzE0MjgsIm5iZiI6MTcxNjkzMTEyOCwicGF0aCI6Ii83NjY2NDE1Ni8zMzQ1NjUzNDEtNjk0ZDI4MDktYTkyNS00MTBhLWJiY2QtOWFmNWY0YWM2OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIxMTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODM2YWRlZTMzMjE0Mzg4MjU4MTAxNGM1ZmFiYTQ0MDI2ZDdlN2I4MGFmMzJjNDdkZjljYWIzM2ZiODQ1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj1HuFmOulzsEuYoaFlnOzOK_lm7--0VbAtZITGtqAs)

You might want to delete this, your email is showing!

**Comment by its-just-michael** [comment]
iRacing should be changed back to broken. I have no idea what the developer's stances are on the matter anymore, but with an update all online play is broken on Linux (see this fourm thread, hasn't worked since the release of a new season in June: https://forums.iracing.com/discussion/57539/aaaaaand-its-kind-of-back/p11).

**Comment by DanFraserUK** [comment]
I forgot about this!

Would it be classed as broken though?

Test Drive and AI racing *do* work without issue.

**Comment by Starz0r** [comment]
In my opinion, Test Drive and AI racing alone, do not constitute as full Linux support. What this looks like is they are trying to silo of Linux users from being able to do online play, and as such, will move this game back into the "Broken" status until they allow it.

**Comment by DanFraserUK** [comment]
Bit of an update.

No change to the status Broken.

https://github.com/DanFraserUK/iRacing-On-Linux

https://github.com/DanFraserUK/proton-cachyos/releases

Test Drive, AI Racing, Replays and Time Attack are functional - with the proviso At Your Own Risk.
