### ISSUE TITLE
Update Elden Ring to Running

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [AreWeAntiCheatYet/AreWeAntiCheatYet#1662]
### Game Title

Elden Ring

### Status of the Anti-Cheat

~~😥 Broken~~ Running

### Tinkering Steps

Most players need a workaround to fix: manually creating a `DLC.bdt` file in the game's files is enough to get it to work.

After the new update, online play is only working for people that own the game's new DLC, everyone else on Linux is getting an "inappropriate activity detected" error when attempting online play, but can still play offline. More specifically, the anticheat seems to fail to validate if a file related to the DLC isn't present, and that file will not be present if you do not own this DLC. The developer hasn't said anything on this so far, but the current theory is a bad EAC config. This apparently works fine on Windows.

More info: https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-2181650512

### Proof of Mention

https://www.protondb.com/app/1245620?device=any
https://www.gamesradar.com/games/action-rpg/fromsoftware-warns-elden-ring-patch-112-might-stunlock-your-steam-deck-going-inactive-for-more-than-5-minutes-may-stop-the-game-from-accepting-inputs/

**Comment by astrayblackcat** [comment]
From the replies in the same issue linked, the problem can be fixed by creating an empty `DLC.bdt` file in the game's directory alongside all of the other `.bdt` files, in `ELDEN RING/Game`. While not ideal, it's a (worryingly) simple thing to fix.
