### ISSUE TITLE
Update Predator: Hunting Grounds

### ISSUE THREAD

**Issue by GrzybDev** [AreWeAntiCheatYet/AreWeAntiCheatYet#1668]
### Game Title

Predator: Hunting Grounds

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Game and EasyAntiCheat works flawlessly after installing Proton EasyAntiCheat Runtime

### Proof of Mention

https://www.protondb.com/app/1556200

**Comment by spix11** [comment]
Does the anti-cheat work smoothly in the game? There are many comments on Steam about how this program eats up game files and constantly crashes. After all this, I want to ask if it's safe to play Predator Hunting Grounds with this anti-cheat.
