### ISSUE TITLE
Update Vindictus

### ISSUE THREAD

**Issue by yretenai** [AreWeAntiCheatYet/AreWeAntiCheatYet#1670]
### Game Title

Vindictus

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Vindictus has been working out of the box with Proton Experimental for about two years now.

Given almost all Nexon Game Security games haven't been checked in over a year, it's also possible that other NGS games now run (as already proven by Kartrider Drift, Tree of Savior, and Velied Experts) and it's worth checking.

### Proof of Mention

https://www.protondb.com/app/212160

**Comment by yretenai** [comment]
Mabinogi works via the Nexon Game Manager (Lutris), Steam version crashes due to the launcher (workaround may be available?) -- Need more people to test Mabinogi via NGM to be sure.

**Comment by yretenai** [comment]
The First Descendant was [running during the betas](https://www.protondb.com/app/2074920), so at least NGS works. Might disconnect in-game since it now has EAC, need to re-check when it launches in a few days on 2nd of July to get past the pre-download splash screen.

**Comment by Pixelsilzavon77** [comment]
> Mabinogi works via the Nexon Game Manager (Install "Nexon Games" via Lutris), Steam version crashes due to the launcher (workaround may be available?) -- Need more people to test Mabinogi via NGM to be sure.

Mabinogi works perfectly for me through Lutris, with a few settings toggled (specifically turning off the anti cheat settings, and changing to feral game mode)

**Comment by QuentinDOS** [comment]
Mabinogi works fine for me, no tinkering outside of installing it through Heroic Games Launcher and using WINE with the Nexon Launcher.
