### ISSUE TITLE
Update Wuthering Waves

### ISSUE THREAD

**Issue by AQXT1000** [AreWeAntiCheatYet/AreWeAntiCheatYet#1671]
### Game Title

Wuthering Waves

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Install the game using your prefered method (lutris, non-steam game, heroic) and play, the anticheat don't block you anymore since update 1.1, I myself tested this using the official launcher, lutris and wavey launcher (which just launched) and all of them worked (just remember to use proton ge to fix lighting and bloom issues)

Screenshot of me playing:

![Captura de tela de 2024-06-30 14-16-22](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/36634604/07cdad04-441b-4197-a708-ec5f9ed429a0)

### Proof of Mention

https://www.reddit.com/r/WutheringWaves/comments/1dr0k8y/now_working_on_steam_deck/

**Comment by Starz0r** [comment]
Going to wait for more information before marking this one. Could be a false-positive, and don't want to get anyone's hopes up.

**Comment by FocusBlast** [comment]
Can confirm it now works on Steam Deck and Linux.

**Comment by GomezMig03** [comment]
Apparently they just disabled the anti cheat on accident and the game is not working anymore on Linux.

**Comment by Starz0r** [comment]
Look like it's been broken for awhile now, so I'm just going to go ahead and close this one. If the developers happen to change their stance, or some new developments happen on getting it running, feel free to re-open this issue or file a new one.
