### ISSUE TITLE
Update Zenless Zone Zero

### ISSUE THREAD

**Issue by mizztgc** [AreWeAntiCheatYet/AreWeAntiCheatYet#1676]
### Game Title

Zenless Zone Zero

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

This game looks to be playable on release day on Linux through the HoYoPlay launcher, and without any third party patches. Despite this, I'm not sure if the developers will start detecting and banning players for playing the game like this.

edit: I'm using Bottles with soda-8.0-2 as my runner

![Screenshot_20240704_024751](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/assets/156482273/68a7ec97-ded7-4173-a74c-0913583f1c92)

### Proof of Mention

none at the moment

**Comment by GomezMig03** [comment]
I can confirm it works perfectly with Proton Experimental. I don't think they will start banning players because, in both Honkai Star Rail and Genshin Impact, they don't ban anyone playing on Linux.

**Comment by MarlonSdS** [comment]
Can confirm, I've been playing since the launch day with no issues.

**Comment by mybday123** [comment]
There appears to be a memory leak issue on NVIDIA GPUs. On Windows, the game only utilized about half of the VRAM.

![Screenshot from 2024-07-12 22-32-51-2](https://github.com/user-attachments/assets/a9091279-d8fd-489e-8677-0260ad64c420)
