### ISSUE TITLE
Light Theme Error

### ISSUE THREAD

**Issue by MRCYODev** [AreWeAntiCheatYet/AreWeAntiCheatYet#1684]
When I change from a Dark Theme to a Light Theme, it becomes difficult to read the text in the notes.

Default color:  #ffd43b
Darker of default color: #bfb143
My recommendation: #bf4343 - (works perfectly in both modes)

⭐ Additionally, you can add other fonts because the current one is too thin and hard on the eyes.

yours - 
![Screenshot 2024-07-13 085220](https://github.com/user-attachments/assets/28f66e74-9c94-4024-ad44-b37959e09d5d)
![Screenshot 2024-07-13 085228](https://github.com/user-attachments/assets/31a2c7b5-58c6-41cc-b3b2-93ca18ab0e2a)

mine - 
![Screenshot 2024-07-13 085918](https://github.com/user-attachments/assets/0cf0167d-cab1-48bb-b23e-59457d2c71c9)
![Screenshot 2024-07-13 085929](https://github.com/user-attachments/assets/f444ed78-eff8-48e7-a622-09b23c2c6f0d)

**Comment by Curve** [comment]
@Starz0r We should add the color into the mantine theme instead of introducing a variable everywhere we want it to be used. We'd also avoid having to manually check the current active theme then.

**Comment by Starz0r** [comment]
@Curve If you have an example of how it would be done, I could certainly do that. As of now, the current version of Mantine is somewhat frustrating to work with, especially color schemes, where as v5 it wasn't as hard to extend.

Also, there is a few blind spots I missed for the Light Theme, so perhaps those should get covered as well if the Light Theme is revisited later.
