### ISSUE TITLE
Update Lost Light: Add name of identified AC and change game status to Broken.

### ISSUE THREAD

**Issue by WhippuSIF** [AreWeAntiCheatYet/AreWeAntiCheatYet#1688]
### Game Title

Lost Light

### Anti-Cheat Software

Unknown (Custom) → **NACE** ([icon](https://files.catbox.moe/pjjg1b.webp))

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Game is broken on Proton, with some managing to get in only for the game's anti-tamper wrapper to detect Proton as cheating software.

In addition, the name of the anti-tamper wrapper is NACE, which stands for NetEase Anti-Cheat Expert (not to be confused with the other "Anti-Cheat Expert" from Tencent.)

### Proof of Mention

https://www.protondb.com/app/1797880#QixIO99aY6

**Comment by Starz0r** [comment]
@WhippuSIF Where did you get the icon for the anti-cheat?

**Comment by WhippuSIF** [comment]
@Starz0r https://unisdk.nie.netease.com/home/unisec (found at the bottom of the page next to the NetEase Games logo)

**Comment by Starz0r** [comment]
Thanks!
