### ISSUE TITLE
Update League of Legends: Add note that the game works in a Hackintosh VM

### ISSUE THREAD

**Issue by WhippuSIF** [AreWeAntiCheatYet/AreWeAntiCheatYet#1689]
### Game Title

League of Legends

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

- Playable on a Hackintosh VM as the Mac client doesn't use Vanguard.

### Proof of Mention

https://www.reddit.com/r/linux/comments/1abm3qf/play_lol_using_a_macos_vm/

**Comment by Starz0r** [comment]
I'm a bit weary about adding this, since adding attention to this means they might see increased macOS users, perhaps for the specific usecase of cheating. There is also the fact that they might just start trying to detect macOS VMs in the future, definitely needs to be handled cautiously.

**Comment by WhippuSIF** [comment]
@Starz0r I stand corrected.

https://www.leagueoflegends.com/en-us/news/dev/dev-vanguard-x-lol-retrospective/

> Mac x Vanguard (aka Vanguard 2)

>As we were getting at in the “botting” section, some cheaters have begun to pivot to macOS VMs, in an effort to free themselves from the Vanguard requirement. This move was about as unexpected as syrup on pancakes, so we’re pleased to announce that Vanguard’s companion product, Embedded Vanguard (mVG) is coming soon to a Mac build near you. The unique security of the macOS environment allows us to be a little less stringent on defending its kernel, so as the name implies, this won’t require any extra installs—the security is “embedded” right into the game client. Further still, we’re actually already using mVG to great effect on VALORANT console and on Wild Rift.

>Once it ships at the end of this year, we hope it will be the final blow to bots and to the two public scripting suite developers that are now grappling with the realization they wasted three months on porting cheats to OSX. Don’t worry too much though, Swift looks great on a resume.


Issue closed.
