### ISSUE TITLE
Update Heaven Burns Red: Add the game's kernel-mode AC, as well as note that game is playable in Waydroid

### ISSUE THREAD

**Issue by WhippuSIF** [AreWeAntiCheatYet/AreWeAntiCheatYet#1691]
### Game Title

Heaven Burns Red

### Anti-Cheat Software

CrackProof + **WFSDrv** ([icon](https://files.catbox.moe/1dj3x9.webp))

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

The game uses a kernel-mode driver named wfshbr (most likely the same as wfsdrv) in conjunction with CrackProof. CrackProof is just a user-mode packer, like Riot's Packman. Street Fighter V also used CrackProof in the past but removed it earlier this year, and [the game still ran on Proton despite the implementation](https://www.protondb.com/app/310950). It's safe to say that CrackProof isn't the cultprit here.

**Notes:**
- Android port is [playable on Waydroid.](https://www.youtube.com/watch?v=1y-0ZtIGwn4)

### Proof of Mention

https://wfs-heaven-burns-red.zendesk.com/hc/ja/articles/15321228868633--PC%E7%89%88-%E3%82%A2%E3%83%B3%E3%83%81%E3%82%A6%E3%82%A3%E3%83%AB%E3%82%B9%E3%82%BD%E3%83%95%E3%83%88%E3%81%8C%E4%BD%9C%E5%8B%95%E3%81%97%E3%81%A6%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93

**Comment by Starz0r** [comment]
@WhippuSIF Where did you get the icon for the anti-cheat?

**Comment by WhippuSIF** [comment]
@Starz0r Taken from [WFS logo](https://www.wfs.games/assets/img/rebranding/banner_wfs_logo.png) as WFSDrv is their own anti-cheat solution.
https://www.wfs.games/en-us/service/

**Comment by Starz0r** [comment]
Thanks!
