### ISSUE TITLE
Request Spectre Divide 

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [AreWeAntiCheatYet/AreWeAntiCheatYet#1699]
### Game Title

Spectre Divide 

### Game Website

https://www.playspectre.com

### Anti-Cheat Software

BattlEye

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://steamcommunity.com/app/2889840/discussions/0/4513254889539072240/
https://steamcommunity.com/app/2889840/discussions/0/4513254889538549956/
Moreover, myself. I got accepted into the Playtest, and when launching it, we get stopped by a window explicitly stating that wine isn't supported.
![image](https://github.com/user-attachments/assets/2c8f6270-a787-4b13-a1de-8d7b57a0a4e0)
I didn't count this error message as a proof, as it may be a default message of Battle-eye when support isn't enabled, which seems to be a default.

UPDATE : Update from Broken to Denied as mentioned in this interview : https://www.theverge.com/24211078/spectre-divide-preview-mountaintop-fps-game

> It’s only currently planned for PC, with no controller or console plans yet — and Mountaintop won’t necessarily allow Steam Deck to join. “__Steam Deck is a concern as a cheating vector, and I think our anti-cheat systems may block it right now__,” Mountaintop CEO and cofounder Nate Mitchell tells me.

**Comment by Starz0r** [comment]
That does look like the default Wine error message in new versions of BattlEye. I'll sit on this for a few days before assigning this one.

**Comment by PoorPocketsMcNewHold** [comment]
Haven't marked it as confirmed as such, but just plain broken. Still waitung for any official statement while they are running play & stress-tests

**Comment by PoorPocketsMcNewHold** [comment]
UPDATE : Update from Broken to Denied as mentioned in this interview : [theverge.com/24211078/spectre-divide-preview-mountaintop-fps-game](https://www.theverge.com/24211078/spectre-divide-preview-mountaintop-fps-game)

    It’s only currently planned for PC, with no controller or console plans yet — and Mountaintop won’t necessarily allow Steam Deck to join. “Steam Deck is a concern as a cheating vector, and I think our anti-cheat systems may block it right now,” Mountaintop CEO and cofounder Nate Mitchell tells me.

**Comment by Schutzend** [comment]
Confirmation of Support for Proton's denial of support for Linux
![image](https://github.com/user-attachments/assets/7ab9208b-d14b-440b-91bd-91d40ca93ca1)
