### ISSUE TITLE
Update Genshin Impact

### ISSUE THREAD

**Issue by danilw** [AreWeAntiCheatYet/AreWeAntiCheatYet#1701]
### Game Title

Genshin Impact

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Genshin in last 2 patches have 100% CPU usage bug only in Linux. (I mean - seems it not going to be fixed)
It very bad especially for Steam Deck-like devices.

There is workaround - offline launch.

**Request to Add link to reddit discussion** - https://www.reddit.com/r/linux_gaming/comments/1ddlfly/genshin_100_cpu_usage_since_today/

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/1ddlfly/genshin_100_cpu_usage_since_today/

**Comment by ElryDeveloper** [comment]
So where is the change exactly ? Genshin is already marked as "Running"
Its still running or would you say the 100% CPU would warrant a "Broken" state ?

**Comment by danilw** [comment]
I asking to add information to this:
![img](https://github.com/user-attachments/assets/b393d77d-ccf6-4443-a19e-c56399424148)

*Notes* column.
Information - link to reddit with note about "offline launch to fix 100% CPU usage".

Same done on many other games on website list.

**Comment by ElryDeveloper** [comment]
yes that makes sense
