### ISSUE TITLE
Remove Paragon: The Overprime

### ISSUE THREAD

**Issue by raspin0** [AreWeAntiCheatYet/AreWeAntiCheatYet#1702]
The game has been shut down.

https://www.reddit.com/r/paragon/comments/1awy5az/paragon_the_overprime_the_game_is_shutting_down/
https://store.steampowered.com/app/1531430/Paragon_The_Overprime/

**Comment by Starz0r** [comment]
I've decided that games shouldn't be removed, but rather marked as shut down. So going forward we'll be doing that in the future. This way is more flexible, and we get to keep the data around about the game when it was still functional.
