### ISSUE TITLE
Request Breachers

### ISSUE THREAD

**Issue by BoofOof32** [AreWeAntiCheatYet/AreWeAntiCheatYet#1705]
### Game Title

Breachers

### Game Website

https://www.breachersvr.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

👍 Running

### Proof of Mention

https://www.protondb.com/app/1922010

**Comment by Patola** [comment]
Breachers has not been working anymore and the developers confirmed in an email and in their discord that they don't whitelist Linux on their EAC configuration.
