### ISSUE TITLE
Remove Blue Protocol

### ISSUE THREAD

**Issue by Schutzend** [AreWeAntiCheatYet/AreWeAntiCheatYet#1712]
On AreWeAntiCheatYet, the game Blue Protocol is marked as Broken using EAC with the note "Unreleased, Speculative". 
The Japan servers will be closed on 02/18/2025 and the game has been canceled in the West. 
So I think we can remove the game from the list. 

Proof of mention: 
https://www.jeuxonline.info/actualite/64543/blue-protocol-ferme-japon-annule-occident
https://www.jvfrance.com/mmorpg-blue-protocol-annule-et-definitivement-ferme-253321/

**Comment by Starz0r** [comment]
Closing this as I've decided we're going to do something with closed/shutdown games. More information here: https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/issues/1702#issuecomment-2323512817
