### ISSUE TITLE
Update Gumdam Evolution

### ISSUE THREAD

**Issue by zturtleman** [AreWeAntiCheatYet/AreWeAntiCheatYet#1720]
### Game Title

Gumdam Evolution

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

This live-service game shutdown in November 2023. It's not playable unrelated to anti-cheat. I don't know what status is appropriate for this or if the game should be removed from the list.

### Proof of Mention

https://steamcommunity.com/games/1816670/announcements/detail/3873720583818478180

**Comment by WhippuSIF** [comment]
EoS'd titles don't count as denied titles. Maybe a EoS disclaimer would suffice?

**Comment by zturtleman** [comment]
Yeah, that would be useful.

**Comment by Starz0r** [comment]
Planning to add a "defunct" or "end of service" field to games, as I'd rather not remove titles from the manifest. So expect that some time soon.
