### ISSUE TITLE
Update Concord

### ISSUE THREAD

**Issue by Weather-OS** [AreWeAntiCheatYet/AreWeAntiCheatYet#1723]
### Game Title

Concord

### Status of the Anti-Cheat

⭕️ To be removed.

### Details

Remove the game from the list as:
A) It’s no longer available for purchase on the steam store
B) it’s servers are shutting down on September 6th.

### Proof of Mention

https://blog.playstation.com/2024/09/03/an-important-update-on-concord/

**Comment by Starz0r** [comment]
As much as I'd like to remove this game, I'm planning to add a new field for games on the manifest that detail if they're defunct or not. So I'd rather keep this entry around for historical accuracy, but rest assured, I will get around to this game.
