### ISSUE TITLE
Update fallguys and add rocket league (regular ver)

### ISSUE THREAD

**Issue by Totallynotmwa** [AreWeAntiCheatYet/AreWeAntiCheatYet#1724]
### Game Title

Fallguys

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

fallguys: Remove available on steam  as they killed off the steam version 2 years ago
![image](https://github.com/user-attachments/assets/0cdbb3dc-10f5-4288-8a34-fa0afe285806)

### Proof of Mention

https://store.steampowered.com/app/1097150/Fall_Guys/

**Comment by Starz0r** [comment]
I'm not even sure what you want done here? The only Steam related thing stored in the manifest is the Store ID, which still exists, and will probably stay there for legacy purposes, and the fact that tools pulling the manifest also use it.

As for Rocket League, it uses no anti-cheat by default (unless something has changed, which as far as I can see, nothing has.) So there's nothing to be done there as well.

**Comment by Totallynotmwa** [comment]
> I'm not even sure what you want done here? The only Steam related thing stored in the manifest is the Store ID, which still exists, and will probably stay there for legacy purposes, and the fact that tools pulling the manifest also use it.

Ohh okay 


>As for Rocket League, it uses no anti-cheat by default (unless something has changed, which as far as I can see, nothing has.) So there's nothing to be done there as well.

I didnt want to open 2 issues so i put it into one
