### ISSUE TITLE
Update Throne and Liberty

### ISSUE THREAD

**Issue by Ly-sec** [AreWeAntiCheatYet/AreWeAntiCheatYet#1732]
### Game Title

Throne and Liberty

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

-

### Proof of Mention

Since it wasn't mentioned I can only talk about the experience from me and some friends. It's been working just fine so far.

**Comment by nelsonbelolima** [comment]
I get kicked by Easy Anti-Cheat
Running Arch Linux + Steam (Native) + GE-Proton9-15 + Proton EasyAntiCheat Runtime

![20241001_182822_2](https://github.com/user-attachments/assets/5e7c1594-ebb8-4302-a038-1a6fa6b90d65)

**Comment by Ly-sec** [comment]
> I get kicked by Easy Anti-Cheat
> Running Arch Linux + Steam (Native) + GE-Proton9-15 + Proton EasyAntiCheat Runtime
> 
> ![20241001_182822_2](https://github.com/user-attachments/assets/5e7c1594-ebb8-4302-a038-1a6fa6b90d65)
> 

They did update eac however they also told people to either delete the EAC folder or just reinstall fully. Not having any issues so far since the last update

**Comment by nelsonbelolima** [comment]
Can confirm, it's working after full reinstall. Thanks!
