### ISSUE TITLE
Update: <FragPunk>

### ISSUE THREAD

**Issue by Jitsuzai** [AreWeAntiCheatYet/AreWeAntiCheatYet#1736]
### Game title

FragPunk

### Status of the game anti-cheat

🏃 Running

### Tinkering steps

Works out of the box but doesn't play videos similar to The Finals billboards you have to run it trough GE Proton

### Proof of mention

https://www.protondb.com/app/2943650

### Additional comments

The game seems to no longer run the "NEAC Protect" anticheat instead it launches with EAC window

**Comment by Starz0r** [comment]
Having tried the game personally, there's no EAC window, game still uses NEAC Protect.

**Comment by Jitsuzai** [comment]
Same I just got my code, my friend on Windows told me it uses EAC I figured it was true since the game runs on Linux sorry for that my bad. >w<
