### ISSUE TITLE
Update: Strinova

### ISSUE THREAD

**Issue by XSilverTH** [AreWeAntiCheatYet/AreWeAntiCheatYet#1745]
### Game title

Strinova

### Status of the game anti-cheat

🏃 Running

### Tinkering steps

Buy a steam deck i guess

### Proof of mention

https://www.protondb.com/app/1282270?device=steamDeck

### Additional comments

It only launches on steam decks. launching it on anything else doesn't work. even on systems with steamos installed

**Comment by UsernamesAreNotMyThing** [comment]
It's also worth adding that **Delta Force** and **Dungeonborne** are also having this behavior.
