### ISSUE TITLE
Request: Infinity Nikki

### ISSUE THREAD

**Issue by MarioKart7z** [AreWeAntiCheatYet/AreWeAntiCheatYet#1749]
### Game title

Infinity Nikki

### Game main page

https://infinitynikki.infoldgames.com/en/home

### Anti-cheat software

Other (please specify below)

### Anti-cheat name

Anti Cheat Expert

### Status of the game anti-cheat

☹️ Broken

### Tinkering steps

Attempted:

- Proton Experimental and Proton GE 9-20 through Steam
- kron4ek-wine-9.22-amd64 and Proton GE 9-20 through Bottles
- SteamDeck=1 environment variable present in all tested environments

### Proof of mention

https://www.reddit.com/r/linux_gaming/comments/1h75ev6/steamdeck1_in_the_flatpak_version_of_steam/

### Additional comments

Anti Cheat Expert seems to be specifically checking for the Steam Deck's hardware and refuses to run under Wine under any other circumstance. The game cannot even be installed, as the launcher runs the anti-cheat partway through the download, which is interrupted if the checks fail. This behavior appears consistent with other recent games that use Anti Cheat Expert.

**Comment by MarioKart7z** [comment]
Addendum: Does not work in a virtual machine.

```
ACE Center

This application can not run under a virtual machine.
Please do not run game in virtual environment or system made from virtual environment image.
```

Virtual environment: Windows 10, libvirt+qemu (KVM), GPU IOMMU passthrough

**Comment by mimi89999** [comment]
During install, the `Program Files/InfinityNikkiGlobal Launcher/InfinityNikkiGlobal/X6Game/Binaries/Win64/AntiCheatExpert` folder is created containing the following files:
```
ACE-Base64.dll  ACE-Base.dat  ACE-BASE.sys  ACE-CORE.sys  ACE-CORE.sys2  ACE-CORE.sys3  ACE-CSI64.dll  ACE-Service64.exe  ACE-Setup64.exe
```

**Comment by sifiro** [comment]
@mimi89999 
In Steam Deck too?

**Comment by mimi89999** [comment]
IDK. I tried on a Linux desktop with Wine with Proton
